### ISSUE TITLE
Drag the map under the point

### ISSUE THREAD

**Issue by grischard** [fedus/safe_crossing#14] opened 2021-06-20 16:46 UTC
Tapping to re-centre the blue circle is uncomfortable because my finger is right on top of where I'm trying to tap precisely. The blue circle should be stuck to the screen, and not move when I move the map, so that I can align the map under the circle.

**Comment by fedus** [comment] 2021-07-03 13:37
Duplicate of #8

**Closed as completed by fedus** 2021-07-03 13:37 UTC
Labels: duplicate
